# Use an official Ubuntu runtime as a parent image
FROM ubuntu:18.04

# Install any needed packages specified in requirements.txt
# Install ethereum and geth
RUN apt-get update
RUN apt-get install -y dnsutils
RUN apt-get install -y curl

